version: '2'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms384m -Xmx384m"
        volumes:
            - ./esdata:/usr/share/elasticsearch/data
    kibana:
        image: docker.elastic.co/kibana/kibana:7.1.1
        links:
            - elasticsearch
    screeps-stats:
        build: .
        links:
            - elasticsearch:elasticsearch
    nginx:
        image: nginx
        ports:
            - "3000:80"
        links:
            - kibana
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/htpasswd:/etc/nginx/htpasswd
