version: '2'
services:
    elasticsearch:
        image: elasticsearch
        volumes:
            - ./esdata:/usr/share/elasticsearch/data
    kibana:
        image: kibana
        links:
            - elasticsearch
    screeps-stats:
        build: .
        links:
            - elasticsearch:elasticsearch
        entrypoint: wait-for-it/wait-for-it.sh -t 30 elasticsearch:9200 -- python screeps_etl/screepsstats.py
    nginx:
        image: nginx:1.9.6
        ports:
            - "8000:80"
        links:
            - kibana
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/htpasswd:/etc/nginx/htpasswd
